export const INITIAL_SETTINGS = {
  brideName: 'Sophia Elegant',
  groomName: 'Alexander Royal',
  weddingDate: '2026-11-15',
  totalBudget: 45000,
  currency: '$',
  venueLocation: 'Grand Chateaux & Gardens, New York',
  notes: 'Dream autumn wedding setup with pastel rose and gold themes.'
};

export const INITIAL_PLACES = [
  {
    id: 'place-1',
    name: 'The Rosewood Grand Ballroom',
    category: 'Wedding Hall',
    address: '450 Park Avenue, Midtown',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    contactPerson: 'Elena Rostova',
    phone: '+1 212-555-0199',
    email: 'events@rosewoodballroom.com',
    googleMapsLink: 'https://maps.google.com/?q=Rosewood+Grand+Ballroom',
    notes: 'Main wedding reception hall booked from 4 PM to 11 PM. Includes crystal chandeliers and dance floor.',
    createdAt: '2026-06-01T10:00:00Z'
  },
  {
    id: 'place-2',
    name: 'St. Patrick Grace Sanctuary',
    category: 'Church',
    address: '12 Cathedral Way',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    contactPerson: 'Father Thomas',
    phone: '+1 212-555-0143',
    email: 'sanctuary@stpatrickchurch.org',
    googleMapsLink: 'https://maps.google.com/?q=St+Patrick+Church',
    notes: 'Ceremony venue. Organist confirmed. Rehearsal scheduled for Nov 14 at 5 PM.',
    createdAt: '2026-06-02T11:30:00Z'
  },
  {
    id: 'place-3',
    name: 'Sophia Family Villa (Bride Residence)',
    category: "Bride's House",
    address: '88 Heritage Drive',
    city: 'Scarsdale',
    state: 'NY',
    country: 'USA',
    contactPerson: 'Martha Elegant (Mother)',
    phone: '+1 914-555-0112',
    email: 'martha.elegant@email.com',
    googleMapsLink: 'https://maps.google.com/?q=Scarsdale+NY',
    notes: 'Morning bridal prep, makeup, family tea ceremony, and bridal photo shoot.',
    createdAt: '2026-06-03T09:15:00Z'
  },
  {
    id: 'place-4',
    name: 'Luminary Cine & Photography Studio',
    category: 'Photographer Studio',
    address: '204 Soho Creative Hub',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    contactPerson: 'Marcus Vance',
    phone: '+1 646-555-0188',
    email: 'marcus@luminarycine.com',
    googleMapsLink: 'https://maps.google.com/?q=Luminary+Studio+Soho',
    notes: '2 lead photographers, 1 drone operator, 4K cinematic film output.',
    createdAt: '2026-06-05T14:20:00Z'
  },
  {
    id: 'place-5',
    name: 'Velvet Petal Floral & Decor Studio',
    category: 'Decoration Shop',
    address: '77 Botanical Avenue',
    city: 'Brooklyn',
    state: 'NY',
    country: 'USA',
    contactPerson: 'Chloe Bennett',
    phone: '+1 718-555-0167',
    email: 'chloe@velvetpetaldecor.com',
    googleMapsLink: 'https://maps.google.com/?q=Velvet+Petal+Decor',
    notes: 'White roses, blush peonies, champagne arch setup with golden candle stands.',
    createdAt: '2026-06-08T16:00:00Z'
  },
  {
    id: 'place-6',
    name: 'The Ritz Carlton Suite & Spa',
    category: 'Hotel',
    address: '50 Central Park South',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    contactPerson: 'Concierge Manager',
    phone: '+1 212-555-0100',
    email: 'stay@ritzcarltonny.com',
    googleMapsLink: 'https://maps.google.com/?q=Ritz+Carlton+Central+Park',
    notes: 'Bridal suite booked for 3 nights + 15 guest rooms reserved under wedding block.',
    createdAt: '2026-06-10T12:00:00Z'
  }
];

export const INITIAL_PEOPLE = [
  {
    id: 'guest-1',
    fullName: 'Jonathan Elegant',
    nickname: 'Dad',
    mobileNumber: '+1 914-555-0101',
    email: 'jonathan.elegant@gmail.com',
    gender: 'Male',
    relationship: 'Bride Side',
    placeId: 'place-3',
    address: '88 Heritage Drive, Scarsdale, NY',
    notes: 'Father of the Bride. Giving the toast speech at 7 PM.',
    rsvpStatus: 'Attending',
    invitationSent: true,
    createdAt: '2026-06-12T10:00:00Z'
  },
  {
    id: 'guest-2',
    fullName: 'Beatrice Royal',
    nickname: 'Aunt Bea',
    mobileNumber: '+1 212-555-0202',
    email: 'beatrice.royal@outlook.com',
    gender: 'Female',
    relationship: 'Groom Side',
    placeId: 'place-6',
    address: '105 5th Avenue, NYC',
    notes: 'Groom aunt staying at Ritz Carlton suite block.',
    rsvpStatus: 'Attending',
    invitationSent: true,
    createdAt: '2026-06-13T11:00:00Z'
  },
  {
    id: 'guest-3',
    fullName: 'Liam Sterling',
    nickname: 'Liam',
    mobileNumber: '+1 347-555-0303',
    email: 'liam.sterling@techcorp.io',
    gender: 'Male',
    relationship: 'Friend',
    placeId: 'place-1',
    address: '14 Bayberry Lane, Brooklyn, NY',
    notes: 'Best Man. Managing ring exchange during ceremony.',
    rsvpStatus: 'Attending',
    invitationSent: true,
    createdAt: '2026-06-14T14:10:00Z'
  },
  {
    id: 'guest-4',
    fullName: 'Isabella Crawford',
    nickname: 'Bella',
    mobileNumber: '+1 212-555-0404',
    email: 'isabella.crawford@fashiondaily.com',
    gender: 'Female',
    relationship: 'Friend',
    placeId: 'place-3',
    address: '52 West End Ave, NYC',
    notes: 'Maid of Honor. Assisting with dress changes.',
    rsvpStatus: 'Attending',
    invitationSent: true,
    createdAt: '2026-06-15T15:30:00Z'
  },
  {
    id: 'guest-5',
    fullName: 'Marcus Vance',
    nickname: 'Marcus Studio',
    mobileNumber: '+1 646-555-0188',
    email: 'marcus@luminarycine.com',
    gender: 'Male',
    relationship: 'Vendor',
    placeId: 'place-4',
    address: '204 Soho Creative Hub, NYC',
    notes: 'Lead Cinematographer & Photographer team manager.',
    rsvpStatus: 'Attending',
    invitationSent: true,
    createdAt: '2026-06-16T16:00:00Z'
  },
  {
    id: 'guest-6',
    fullName: 'David & Clara Miller',
    nickname: 'The Millers',
    mobileNumber: '+1 516-555-0505',
    email: 'david.miller@estatepartners.com',
    gender: 'Other',
    relationship: 'Relative',
    placeId: 'place-1',
    address: '12 Harbour Road, Long Island, NY',
    notes: 'Family friends of Groom. 2 attending.',
    rsvpStatus: 'Pending',
    invitationSent: true,
    createdAt: '2026-06-18T09:40:00Z'
  },
  {
    id: 'guest-7',
    fullName: 'Dr. Arthur Pendelton',
    nickname: 'Uncle Art',
    mobileNumber: '+1 617-555-0606',
    email: 'arthur.pendelton@harvard.edu',
    gender: 'Male',
    relationship: 'Groom Side',
    placeId: 'place-6',
    address: '89 Beacon St, Boston, MA',
    notes: 'Travelling from Boston. Flying in on Nov 13.',
    rsvpStatus: 'Attending',
    invitationSent: true,
    createdAt: '2026-06-20T12:00:00Z'
  },
  {
    id: 'guest-8',
    fullName: 'Samantha & Kevin Hayes',
    nickname: 'Sam',
    mobileNumber: '+1 415-555-0707',
    email: 'sam.hayes@designstudio.com',
    gender: 'Female',
    relationship: 'Relative',
    placeId: 'place-6',
    address: '320 Market St, San Francisco, CA',
    notes: 'Awaiting confirmation on flight schedule.',
    rsvpStatus: 'Pending',
    invitationSent: false,
    createdAt: '2026-06-22T14:50:00Z'
  }
];

export const INITIAL_EXPENSES = [
  {
    id: 'exp-1',
    title: 'Rosewood Ballroom Venue Deposit & Rental',
    category: 'Venue',
    amount: 12500,
    date: '2026-06-05',
    paidTo: 'The Rosewood Grand Ballroom',
    paymentMethod: 'Bank Transfer',
    placeId: 'place-1',
    paymentStatus: 'Paid',
    notes: 'Initial 50% deposit paid. Remaining 50% due 14 days before event.',
    createdAt: '2026-06-05T10:00:00Z'
  },
  {
    id: 'exp-2',
    title: 'Gourmet 4-Course Banquet & Bar Service',
    category: 'Catering',
    amount: 9800,
    date: '2026-06-12',
    paidTo: 'Royal Gourmet Catering',
    paymentMethod: 'Card',
    placeId: 'place-1',
    paymentStatus: 'Paid',
    notes: 'Includes champagne toast and custom dessert bar for 120 guests.',
    createdAt: '2026-06-12T14:30:00Z'
  },
  {
    id: 'exp-3',
    title: 'Cinematic Photography & Film Package',
    category: 'Photography',
    amount: 4500,
    date: '2026-06-15',
    paidTo: 'Luminary Cine & Photography Studio',
    paymentMethod: 'UPI',
    placeId: 'place-4',
    paymentStatus: 'Paid',
    notes: 'Full day coverage + highlight reel + photo album.',
    createdAt: '2026-06-15T11:00:00Z'
  },
  {
    id: 'exp-4',
    title: 'Floral Arches & Candle Centerpieces',
    category: 'Decoration',
    amount: 3800,
    date: '2026-06-20',
    paidTo: 'Velvet Petal Floral Studio',
    paymentMethod: 'Bank Transfer',
    placeId: 'place-5',
    paymentStatus: 'Pending',
    notes: 'Deposit paid $1,500. Balance $2,300 scheduled for Nov 1.',
    createdAt: '2026-06-20T16:00:00Z'
  },
  {
    id: 'exp-5',
    title: 'Custom Bridal Gown & Veil Fitting',
    category: 'Dress',
    amount: 3200,
    date: '2026-06-25',
    paidTo: 'Vera Wang Bridal Boutique',
    paymentMethod: 'Card',
    placeId: 'place-3',
    paymentStatus: 'Paid',
    notes: 'Silk gown with lace embroidery and cathedral veil.',
    createdAt: '2026-06-25T13:15:00Z'
  },
  {
    id: 'exp-6',
    title: 'Groom Custom Tuxedo & Accessories',
    category: 'Dress',
    amount: 1400,
    date: '2026-07-01',
    paidTo: 'Tom Ford Tailoring',
    paymentMethod: 'Card',
    placeId: 'place-1',
    paymentStatus: 'Paid',
    notes: 'Midnight blue tuxedo with gold cufflinks.',
    createdAt: '2026-07-01T15:00:00Z'
  },
  {
    id: 'exp-7',
    title: 'Bridal Makeup Artist & Hair Styling',
    category: 'Makeup',
    amount: 950,
    date: '2026-07-05',
    paidTo: 'Glamour Touch Studio',
    paymentMethod: 'Cash',
    placeId: 'place-3',
    paymentStatus: 'Pending',
    notes: 'Includes trial makeup session + 4 bridesmaids styling.',
    createdAt: '2026-07-05T09:30:00Z'
  },
  {
    id: 'exp-8',
    title: 'Live Jazz Band & Ceremony Quartet',
    category: 'Entertainment',
    amount: 2200,
    date: '2026-07-10',
    paidTo: 'Manhattan Sound Artists',
    paymentMethod: 'Bank Transfer',
    placeId: 'place-1',
    paymentStatus: 'Pending',
    notes: 'Quartet for church ceremony + 5-piece Jazz band for cocktail hour.',
    createdAt: '2026-07-10T14:40:00Z'
  }
];

export const INITIAL_CHECKLIST = [
  { id: 'task-1', task: 'Reserve Wedding Ceremony Venue', category: 'Venue', dueDate: '2026-06-05', completed: true },
  { id: 'task-2', task: 'Finalize Photographer & Videographer', category: 'Vendors', dueDate: '2026-06-15', completed: true },
  { id: 'task-3', task: 'Order Wedding Cake & Dessert Tasting', category: 'Catering', dueDate: '2026-07-25', completed: false },
  { id: 'task-4', task: 'Send Save-the-Date Invitations', category: 'Guests', dueDate: '2026-08-01', completed: true },
  { id: 'task-5', task: 'Finalize Floral Arch & Table Themes', category: 'Decoration', dueDate: '2026-08-15', completed: false },
  { id: 'task-6', task: 'Bridal Outfit Final Dress Fitting', category: 'Attire', dueDate: '2026-10-01', completed: false },
  { id: 'task-7', task: 'Confirm Guest Headcount & Seating Chart', category: 'Guests', dueDate: '2026-10-25', completed: false },
  { id: 'task-8', task: 'Rehearsal Dinner Coordination', category: 'Ceremony', dueDate: '2026-11-10', completed: false }
];
